### ISSUE TITLE
Update error state for form fields

### ISSUE THREAD

**Issue by silviatc** [xogroup/union#63] opened 2017-02-22 19:58 UTC
As a form field user
I want to see an error state that isn't the same color as our main CTA
So that I will be able to easily distinguish between the error state and the CTA

**Comment by GeorgeTaveras1231** [comment] 2017-03-29 20:03
@silviatc @catarinatsang What exactly is this referring to? Is this a duplicate of #70? Or could these issues be combined to have one issue related to fields?

**Comment by pkelly** [comment] 2017-04-20 17:30
I created a new issue for all form field styling updates which includes this
#113

**Closed by pkelly** 2017-04-20 17:30 UTC
