### ISSUE TITLE
Component Request - Generic Typeahead

### ISSUE THREAD

**Issue by marioharper** [xogroup/union#204] opened 2017-07-21 15:21 UTC
New Component Request
===

## Description
There should be a **generic** `Typeahead` component in `@xo-union/tk-component-fields`. The Knot uses typeaheads in 2 instances that I know of (Vendor Typeahead, Location Typeahead). This is not a request for those instances, it is a request for a generic component that will aid in the creation of those instances.

### Location Typeahead
![screen shot 2017-07-21 at 10 15 36 am](https://user-images.githubusercontent.com/7682104/28470072-21b41a7e-6dfe-11e7-81ac-d6dfc3d3b417.png)

### Vendor Typeahead
![screen shot 2017-07-21 at 10 16 07 am](https://user-images.githubusercontent.com/7682104/28470076-265e97d4-6dfe-11e7-861d-5f5043cb5691.png)

**Comment by GeorgeTaveras1231** [comment] 2017-07-24 19:41
Timeline: Thurday 27th, July

**Comment by hsbacot** [comment] 2017-07-28 03:45
PR on track for tomorrow. Sorry about the delay.

**Comment by GeorgeTaveras1231** [comment] 2017-08-02 19:48
@marioharper @hsbacot I noticed that with the components from #231 we are still missing a lot of the integration steps between the field and the list of results. Are there plans from anyone to implement the specific components? Example: `LocationTypeahead`.

**Comment by hsbacot** [comment] 2017-08-02 21:01
@GeorgeTaveras1231 There are no plans to support fetching data, that functionality should be composed by the consumer. The consumer should be able to use this list for any type of suggestions provided from an api or otherwise. They would manage the state of the input, the state of the requests, and be able to compose a typeahead by supplying the data to `SuggestionsList`

**Comment by marioharper** [comment] 2017-08-02 23:00
I agree with @hsbacot, this should be generic for flexibility. We could author a `LocationTypeahead` plugin/module that utilizes this component though. I think Union itself should stay generic and stay as the building blocks, however, we could author separate plugins/modules that are created using Union that are used specifically by XO Group. This modules do not need to be publicly facing like Union is. They would be internal implementations. Any thoughts?

**Comment by GeorgeTaveras1231** [comment] 2017-08-02 23:16
@marioharper @hsbacot I'm not suggesting to dump the generic implementation for the specific one, they are both useful to have. @marioharper I agree and that's exactly what I was getting at: We will have the generic implementation available after #231 is merged but it would be useful to have a package for the specific use cases of this component. As far as where it should live, I would be ok with it living elsewhere if there were some benefits to doing that. To me it would seem like separation for the sake of separation. 

I would much rather keep that package in this repository because:

- We can make atomic changes that touch the generic and the specific implementation 
> This makes keeping the specific implementation up to date way easier

- It is easy to refactor and create new packages
> If there is some more reusable code in the specific implementations, it is really easy to distribute that separately

- We have a reasonable build process for managing all of these inter-dependent components -- and it will only get better
> Things we can do today: unit testing, benchmarking, preview changes, document
Things we will be doing in the future: Budget monitoring (size and speed), Visual regression testing

**Comment by marioharper** [comment] 2017-08-02 23:20
That's cool with me, in order to protect our endoints, are we planning on the consumer to pass in the endpoint along with any key?

---- On Wed, 02 Aug 2017 16:16:31 -0700 notifications@github.com wrote ----

@marioharper @hsbacot I'm not suggesting to dump the generic implementation for the specific one, they are both useful to have. @marioharper I agree and that's exactly what I was getting at: We will have the generic implementation available after #231 is merged but it would be useful to have a package for the specific use cases of this component. As far as where it should live, I would be ok with it living elsewhere if there were some benefits to doing that. To me it would seem like separation for the sake of separation.

I would much rather keep that package in this repository because:

We can make atomic changes that touch the generic and the specific implementation
This makes keeping the specific implementation up to date way easier

It is easy to refactor and create new packages
If there is some more reusable code in the specific implementations, it is really easy to distribute that separately

We have a reasonable build process for managing all of these inter-dependent components -- and it will only get better
Things we can do today: unit testing, benchmarking, preview changes, document
Things we will be doing in the future: Budget monitoring (size and speed), Visual regression testing

**Comment by GeorgeTaveras1231** [comment] 2017-08-02 23:25
@marioharper  There is very little we can do to actually protect the endpoints since all code will be visible on the client side anyways. But yes, my theory is that any code that makes API calls should allow the endpoint to be overridden, but should also come with reasonable defaults.

**Comment by GeorgeTaveras1231** [comment] 2017-08-02 23:27
If keys are used to identify clients from one-another (Maybe membership wants to know whether the request is coming from inbox or from glm) then api key should be a required param. If there is a key that applies to all of TK, then defaulting to that key makes sense and allowing it to be overridden.

**Comment by marioharper** [comment] 2017-08-03 19:16
Closing this issue since it was a request for generic typeahead and #231 implemented that. If we need VendorTypeahead or LocationTypeahead, those should be opened up as additional component requests.

**Closed** 2017-08-03 19:16 UTC
Labels: component-request, in progress
